motor_controller:
  ros__parameters:
    pid:
      kp: 1.2
      ki: 0.0
      kd: 0.0
    limits:
      max_rpm: 20

steering_controller:
  ros__parameters:
    steering:
      mode: "diff" # "diff" | "ackermann"
      ack_step_deg: 5
      ack_min: 45
      ack_max: 135
